---
- name: "Removing Default Version of Firefox"
  apt:
    name: firefox-esr
    state: absent
  become: true
  become_method: sudo

- name: "Downloading and Installing Keys to Download Firefox"
  shell: |
    wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | sudo tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
    echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | sudo tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
    echo '
    Package: *
    Pin: origin packages.mozilla.org
    Pin-Priority: 1000
    ' | sudo tee /etc/apt/preferences.d/mozilla

- name: "Installing Firefox"
  apt:
    name: firefox
    state: present
    update_cache: true
  become: true
  become_method: sudo
