---
main_dependencies:
  - build-essential
  - libxcb-keysyms1-dev
  - libxcb-xtest0-dev

polybar_dependencies:
  - cmake
  - cmake-data
  - pkg-config
  - python3-sphinx
  - libcairo2-dev
  - libxcb-util0-dev
  - libxcb-randr0-dev
  - python3-xcbgen
  - xcb-proto
  - libxcb-ewmh-dev
  - libxcb-icccm4-dev
  - libxcb-xkb-dev
  - libxcb-xrm-dev
  - libxcb-cursor-dev
  - libasound2-dev
  - libpulse-dev
  - libjsoncpp-dev
  - libmpdclient-dev
  - libuv1-dev
  - libnl-genl-3-dev

picom_dependencies:
  - meson
  - picom
  - libxext-dev
  - libxcb1-dev
  - libxcb-damage0-dev
  - libxcb-xfixes0-dev
  - libxcb-shape0-dev
  - libxcb-render-util0-dev
  - libxcb-render0-dev
  - libxcb-composite0-dev
  - libxcb-image0-dev
  - libxcb-present-dev
  - libxcb-xinerama0-dev
  - libpixman-1-dev
  - libdbus-1-dev
  - libconfig-dev
  - libgl1-mesa-dev
  - libpcre2-dev
  - libevdev-dev
  - uthash-dev
  - libev-dev
  - libx11-xcb-dev
  - libxcb-glx0-dev
  - libpcre3
  - libpcre3-dev

applications:
  - kitty
  - feh
  - scrot
  - scrub
  - rofi
  - xclip
  - bat
  - locate
  - ranger
  - neofetch
  - wmname
  - acpi
  - bspwm
  - sxhkd
  - imagemagick
  - cmatrix
  - lsd
